task_name: l2reg_pt_ax_densenet201_maxpooling
dataset: out/preprocessed_datasets/step_split/axial_dataset
options:
    architecture: DenseNet201
    method: pretrain
    kaggle: False    
    pooling: max # This has given better results (image size)
    epochs: 150
    batch_size: 32 # this is a very large model
    overrides:
        optimizer_name: SGD # This has given better results
        l2reg: 0.0005