task_name: {str}
dataset: {str}
options:
    architecture: VGG16 | VGG19 | ResNet50 | ResNet152 | DenseNet121 | DenseNet201
    method: pretrain | transferlearn
    pooling: null | avg | max
    learning_rate: {float}
    epochs: {int}
    batch_size: {int}
    overrides:
        optimizer_name: null | Adam | SGD
        l2reg: null | {float}
        dropout: null | {float}
        learning_rate: null | {float}