task_name: pt_ax_densenet201_maxpooling
dataset: out/preprocessed_datasets/adni_processed/axial_dataset
options:
    architecture: DenseNet201
    method: pretrain
    pooling: max 
    epochs: 100
    batch_size: 32 