task_name: pt_ax_resnet152_maxpooling
dataset: out/preprocessed_datasets/adni_processed/axial_dataset
options:
    architecture: ResNet152
    method: pretrain
    pooling: max 
    epochs: 100
    batch_size: 32 