task_name: pt_ax_densenet201_avgpooling
dataset: out/preprocessed_datasets/adni_processed/axial_dataset
options:
    architecture: DenseNet201
    method: pretrain
    pooling: avg 
    epochs: 100
    batch_size: 32 