task_name: pt_ax_vgg16_maxpooling
dataset: out/preprocessed_datasets/adni_processed/axial_dataset
options:
    architecture: VGG16
    method: pretrain

    pooling: max 
    epochs: 100
    batch_size: 32 