task_name: pt_ax_resnet50_maxpooling
dataset: out/preprocessed_datasets/adni_processed/axial_dataset
options:
    architecture: ResNet50
    method: pretrain
    pooling: max # This has given better results (image size)
    epochs: 100
    batch_size: 32 # can take longer to run