task_name: resnet152_pretrain_kaggle
dataset: out/preprocessed_datasets/kaggle_processed
options:
    architecture: ResNet152
    method: pretrain
    kaggle: True    
    pooling: null
    epochs: 200
    batch_size: 16 # Lowered batch size for memory concerns