task_name: tl_ax_vgg16_maxpooling_SGD
dataset: out/preprocessed_datasets/adni_processed/axial_dataset
options:
    architecture: VGG16
    method: transferlearn
    pooling: max 
    epochs: 100
    batch_size: 32
    overrides:
        optimizer_name: SGD # This has given better results