task_name: tl_ax_vgg16_avgpooling_Adam
dataset: out/preprocessed_datasets/adni_processed/axial_dataset
options:
    architecture: VGG16
    method: transferlearn
    pooling: avg 
    epochs: 100
    batch_size: 32
    overrides:
        optimizer_name: Adam # This has given better results