task_name: tl_ax_densenet201_maxpooling_Adam
dataset: out/preprocessed_datasets/adni_processed/axial_dataset
options:
    architecture: DenseNet201
    method: transferlearn
    pooling: max 
    epochs: 100
    batch_size: 32
    overrides:
        optimizer_name: Adam # This has given better results