task_name: tl_ax_resnet152_avgpooling_SGD
dataset: out/preprocessed_datasets/adni_processed/axial_dataset
options:
    architecture: ResNet152
    method: transferlearn
    pooling: avg 
    epochs: 100
    batch_size: 32
    overrides:
        optimizer_name: SGD # This has given better results