task_name: densenet201_pretrain_slices
dataset: out/preprocessed_datasets/adni_processed/slice_dataset
options:
    architecture: DenseNet201
    method: pretrain
    kaggle: False    
    pooling: null
    epochs: 200
    batch_size: 16 # Lowered batch size for memory concerns