task_name: pt_ax_densenet121_nopooling
dataset: out/preprocessed_datasets/adni_processed/axial_dataset
options:
    architecture: DenseNet121
    method: pretrain
    pooling: null 
    epochs: 100
    batch_size: 32 