task_name: pt_ax_vgg19_nopooling
dataset: out/preprocessed_datasets/adni_processed/axial_dataset
options:
    architecture: VGG19
    method: pretrain
    pooling: null 
    epochs: 100
    batch_size: 32 