task_name: resnet152_tl_mc_nopooling_smalldropout_sgd_64bs_updatedaug
dataset: out/preprocessed_datasets/unique/multichannel_slices
options:
    architecture: ResNet152
    method: transferlearn
    kaggle: False    
    pooling: null
    fc_count: 1
    epochs: 100 # these can take long to converge
    batch_size: 64
    overrides:
        optimizer_name: SGD
        l2reg: null
        dropout: 0.3
        learning_rate: null