task_name: tl_mc_resnet152
dataset: out/preprocessed_datasets/unique/multichannel_slices_loweredrange
options:
    architecture: ResNet152
    method: transferlearn
    kaggle: False    
    pooling: null
    fc_count: 1
    epochs: 100 # these can take long to converge
    batch_size: 64
    overrides:
        optimizer_name: Adam
        l2reg: null
        dropout: null
        learning_rate: null