task_name: pt_ax_densenet121_maxpooling
dataset: out/preprocessed_datasets/adni_processed/axial_dataset
options:
    architecture: DenseNet121
    method: pretrain
    kaggle: False    
    pooling: max # This has given better results (image size)
    epochs: 100
    batch_size: 32 # this is a very large model