task_name: tl_ax_resnet152_maxpooling_SGD
dataset: out/preprocessed_datasets/step_split/axial_dataset
options:
    architecture: ResNet152
    method: transferlearn
    kaggle: False    
    pooling: max # This has given better results (image size)
    epochs: 100
    batch_size: 32
    overrides:
        optimizer_name: SGD # This has given better results